services:
  - type: web
    name: classroom-integration
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:10000 app:app --timeout 180
    envVars:
      - key: SECRET_KEY
        generateValue: true